### PR TITLE
Serialized Layer Introspection [Fixes #517]

### LINKED ISSUE #517: Wrong Serialization of an IPv6HopByHop packet
I'm experiencing an error when serializing IPv6HopByHop packets.

The problem, to be exact, is that the HopByHop header is written twice to the buffer.

It's very easy to replicate this problem:

```go
// in icmp6hopbyhop_test.go
func TestPacketICMPv6WithHopByHop(t *testing.T) {
  // add this after the original code
  checkSerialization(p, t)
}

// I've added the checkSerialization() function to `base_test.go`

// Checks that when a serialized version of p is decoded, p and the serialized version of p are the same.
// Does not work for packets where the order of options can change, like icmpv6, dhcpv6, etc.
func checkSerialization(p gopacket.Packet, t *testing.T) {
	buf := gopacket.NewSerializeBuffer()
	opts := gopacket.SerializeOptions{
		ComputeChecksums: false,
		FixLengths: false,
	}
	if err := gopacket.SerializePacket(buf, opts, p); err != nil {
		t.Error("Failed to encode packet:", err)
	}

	p2 := gopacket.NewPacket(buf.Bytes(), LinkTypeEthernet, gopacket.Default)
	if p2.ErrorLayer() != nil {
		t.Error("Failed to decode the re-encoded packet:", p2.ErrorLayer().Error())
	}

	if p2.Dump() != p.Dump() {
		t.Errorf("The decoded and the re-encoded packet are different!\nDecoded:\n%s\n Re-Encoded:\n%s", p.Dump(), p2.Dump())
	}
}
```

The resulting packet looks like this:

        -- FULL PACKET DATA (198 bytes) ------------------------------------
        00000000  33 33 00 00 00 16 1e c3  e3 b7 c4 d5 86 dd 60 00  |33............`.|
        00000010  00 00 00 88 00 01 00 00  00 00 00 00 00 00 00 00  |................|
        00000020  00 00 00 00 00 00 ff 02  00 00 00 00 00 00 00 00  |................|
        00000030  00 00 00 00 00 16 3a 00  05 02 00 00 01 00 3a 00  |......:.......:.|
        00000040  05 02 00 00 01 00 8f 00  9e ed 00 00 00 06 03 00  |................|
        00000050  00 00 ff 02 00 00 00 00  00 00 00 00 00 01 ff b7  |................|
        00000060  c4 d5 03 00 00 00 ff 02  00 00 00 00 00 00 00 00  |................|
        00000070  00 01 ff 00 00 00 04 00  00 00 ff 02 00 00 00 00  |................|
        00000080  00 00 00 00 00 01 ff 11  00 79 04 00 00 00 ff 02  |.........y......|
        00000090  00 00 00 00 00 00 00 00  00 01 ff 00 00 01 04 00  |................|
        000000a0  00 00 ff 05 00 00 00 00  00 00 00 00 00 00 00 00  |................|
        000000b0  00 02 04 00 00 00 ff 02  00 00 00 00 00 00 00 00  |................|
        000000c0  00 00 00 00 00 02                                 |......|
        --- Layer 1 ---
        Ethernet	{Contents=[..14..] Payload=[..184..] SrcMAC=1e:c3:e3:b7:c4:d5 DstMAC=33:33:00:00:00:16 EthernetType=IPv6 Length=0}
        00000000  33 33 00 00 00 16 1e c3  e3 b7 c4 d5 86 dd        |33............|
        --- Layer 2 ---
        IPv6	{Contents=[..40..] Payload=[..136..] Version=6 TrafficClass=0 FlowLabel=0 Length=136 NextHeader=IPv6HopByHop HopLimit=1 SrcIP=:: DstIP=ff02::16 HopByHop={ Contents=[..8..] Payload=[..136..] NextHeader=ICMPv6 HeaderLength=0 ActualLength=8 Options=[{OptionType=5 OptionLength=2 ActualLength=4 OptionData=[0, 0] OptionAlignment=[0 0]}, {OptionType=1 OptionLength=0 ActualLength=2 OptionData=[] OptionAlignment=[0 0]}]}}
        00000000  60 00 00 00 00 88 00 01  00 00 00 00 00 00 00 00  |`...............|
        00000010  00 00 00 00 00 00 00 00  ff 02 00 00 00 00 00 00  |................|
        00000020  00 00 00 00 00 00 00 16                           |........|
        --- Layer 3 ---
        IPv6HopByHop	{Contents=[..8..] Payload=[..136..] NextHeader=ICMPv6 HeaderLength=0 ActualLength=8 Options=[{OptionType=5 OptionLength=2 ActualLength=4 OptionData=[0, 0] OptionAlignment=[0 0]}, {OptionType=1 OptionLength=0 ActualLength=2 OptionData=[] OptionAlignment=[0 0]}]}
        00000000  3a 00 05 02 00 00 01 00                           |:.......|
        --- Layer 4 ---
        ICMPv6	{Contents=[58, 0, 5, 2] Payload=[..132..] TypeCode=58(0) Checksum=1282 TypeBytes=[]}
        00000000  3a 00 05 02                                       |:...|
        --- Layer 5 ---
        Payload	132 byte(s)
        00000000  00 00 01 00 8f 00 9e ed  00 00 00 06 03 00 00 00  |................|
        00000010  ff 02 00 00 00 00 00 00  00 00 00 01 ff b7 c4 d5  |................|
        00000020  03 00 00 00 ff 02 00 00  00 00 00 00 00 00 00 01  |................|
        00000030  ff 00 00 00 04 00 00 00  ff 02 00 00 00 00 00 00  |................|
        00000040  00 00 00 01 ff 11 00 79  04 00 00 00 ff 02 00 00  |.......y........|
        00000050  00 00 00 00 00 00 00 01  ff 00 00 01 04 00 00 00  |................|
        00000060  ff 05 00 00 00 00 00 00  00 00 00 00 00 00 00 02  |................|
        00000070  04 00 00 00 ff 02 00 00  00 00 00 00 00 00 00 00  |................|
        00000080  00 00 00 02                                       |....|

See, the IPv6 Hop-By-Hop option `3a 00 05 02` is written twice:

                                    |----------|             |----
        00000030  00 00 00 00 00 16 3a 00  05 02 00 00 01 00 3a 00  |......:.......:.|
        00000040  05 02 00 00 01 00 8f 00  9e ed 00 00 00 06 03 00  |................|
                  ----|

### PR DESCRIPTION
**Pull request by cimnine**
This PR adds a way for the current layer to see all the layers that were successfully serialized before the current layer, during the serialization of the current layer.

I've come up with this solution in an attempt to fix #517 in a clean way, i.e. without inspecting the actual buffer. I believe the method I've chosen can be useful for other serialization implementations, like such that have the same challenges as described in #517. (tl;dr: Information is present in the "main layer" but also in a separate layer, but must not be serialized twice).

It's important to understand that the solution, as implemented, always prefers the information present in the extra layer over the information present in the "main layer". E.g. in #517, the HopByHop information of the IPv6 layer is ignored when an IPv6HopByHop layer was serialized before.

Bonus: I've cleaned up the `golint` errors in `ip6.go`. As a reviewer you might want to review this PR commit by commit.

### CODE REVIEW

File: writer.go [hunk 1]
```diff
@@ -171,9 +180,18 @@ func (w *serializeBuffer) AppendBytes(num int) ([]byte, error) {
 func (w *serializeBuffer) Clear() error {
 	w.start = w.prepended
 	w.data = w.data[:w.start]
+	w.layers = []LayerType{}
```
Comment (gconnell) [inline writer.go]: change to:

```go
w.layers = w.layers[:0]
```

to avoid a malloc each time Clear() is called.

**Comment by gconnell** [comment]
Thanks for the great PR!
