### PR TITLE
Fix pf_ring 7.2 and maybe performance issues. This fixes #467, #419

### LINKED ISSUE #467: Build fails when using 'pfring 7.2.0-stable'
**vendor/github.com/google/gopacket/pfring/pfring.go:155: r.pkthdr.extended_hdr.if_index undefined (type C.struct_pfring_extended_pkthdr has no field or method if_index)**

   

- PF_RING/kernel/linux/pf_ring.h  (branch 7.2.0-stable)
```
struct pfring_extended_pkthdr {
  u_int64_t timestamp_ns;  /* Packet timestamp at ns precision. Note that if your NIC supports
                  hardware timestamp, this is the place to read timestamp from */
#define PKT_FLAGS_CHECKSUM_OFFLOAD    1 << 0 /* IP/TCP checksum offload enabled */
#define PKT_FLAGS_CHECKSUM_OK         1 << 1 /* Valid checksum (with IP/TCP checksum offload enabled) */
#define PKT_FLAGS_IP_MORE_FRAG        1 << 2 /* IP More fragments flag set */
#define PKT_FLAGS_IP_FRAG_OFFSET      1 << 3 /* IP fragment offset set (not 0) */
#define PKT_FLAGS_VLAN_HWACCEL        1 << 4 /* VLAN stripped by hw */
#define PKT_FLAGS_FLOW_OFFLOAD_UPDATE 1 << 6 /* Flow update metadata, see generic_flow_update struct (keep flag compatible with ZC) */
#define PKT_FLAGS_FLOW_OFFLOAD_PACKET 1 << 7 /* Flow raw packet, pkt_hash contains the flow_id (keep flag compatible with ZC) */
#define PKT_FLAGS_FLOW_OFFLOAD_MARKER 1 << 8 /* Flow raw packet belongs to a flow that has been marked (keep flag compatible with ZC) */
  u_int32_t flags;

  u_int8_t rx_direction;   /* 1=RX: packet received by the NIC, 0=TX: packet transmitted by the NIC */
  int32_t  if_index;       /* index of the interface on which the packet has been received.
                  It can be also used to report other information */
  u_int32_t pkt_hash;      /* Hash based on the packet header */

  /* --- short header ends here --- */

  struct {
    int32_t bounce_interface; /* Interface Id where this packet will bounce after processing
                 if its values is other than UNKNOWN_INTERFACE */
    struct sk_buff *reserved; /* Kernel only pointer */
  } tx;

  /* NOTE: leave it as last field of the memset on parse_pkt() will fail */
  struct pkt_parsing_info parsed_pkt; /* packet parsing info */
} __attribute__((packed));

/* NOTE: Keep 'struct pfring_pkthdr' in sync with 'struct pcap_pkthdr' */

struct pfring_pkthdr {
  /* pcap header */
  struct timeval ts;    /* time stamp */
  u_int32_t caplen;     /* length of portion present */
  u_int32_t len;        /* length of whole packet (off wire) */
  struct pfring_extended_pkthdr extended_hdr; /* PF_RING extended header */
} __attribute__((packed));

```

The structure seems to have not changed from the previous version, but a build error occurs.

### LINKED ISSUE #543: pf_ring read packet slow with cgo
I use the go interface of af_packet and pf_ring to capture packets. I find the the pfring.ReadPacketDataTo() function takes three times as much time as afpacket.ReadPacketDataTo().
Both of these two function call the C interface with Cgo. What the reason of this difference ?
Is that the reason that pfring.ReadPacketDataTo() call the Cgo more frequently and afpacket.ReadPacketDataTo() avoid to call Cgo each packet? And the consumption of Cgo is very large.

In pfring.ReadPacketDataTo(), each packet reading operation will call Cgo by **C.pfring_readpacketdatato_wrapper**:
```go
r.bufPtr = (*C.u_char)(unsafe.Pointer(&data[0]))
	result := NextResult(C.pfring_readpacketdatato_wrapper(r.cptr, r.bufPtr, C.u_int(len(data)),  &r.pkthdr))  //cgo
}
```
However,in afpacket.ReadPacketDataTo(), the function avoid to call Cgo each packet reading.(It read a block of packets at each Cgo(**h.pollForFirstPacket**) operation )
```go
retry:
	if h.current == nil || !h.headerNextNeeded || !h.current.next() {
		if h.shouldReleasePacket {
			h.releaseCurrentPacket()
		}
		h.current = h.getTPacketHeader()
		if err = h.pollForFirstPacket(h.current); err != nil {
			h.headerNextNeeded = false
			//h.mu.Unlock()
			return
		}
		// We received an empty block
		if h.current.getLength() == 0 {
			goto retry
		}
	}
```

### PR DESCRIPTION
**Pull request by notti**
Rework of the core parts of pfring. Due to the use of packed structures in
7.2 cgo can't access some fields of `struct pfring_pkthdr`.
This copies the needed fields to a non-packed struct first.

To improve speed, `pfring_recv` is now called with a length of zero,
enabling zero copy. The old version caused the userlab pf_ring library
to copy the packet contents. This maybe fixes #543, #185.
Additionally, pfring now uses `timestamp_ns` instead of `ts`, which increases
the timestamp resolution from microsecond to nanosecond. Furthermore,
cgo usage was improved by using the same techniques as in pcap
(allocations on the heap).

Added `ZeroCopyReadPacketData`. This one uses not zero copy from kernel
space directly to the buffer. The old `ReadPacketDataTo` caused pf_ring
userspace library to copy the data (buffer_len != 0). The new
`ReadPacketDataTo` still does the copy (but now in gocode) since zero
copy is not possible with the current interface. This method is there to
keep legacy code working, but newer versions should switch over to
`ZeroCopyReadPacketData`.

The following benchmarks were performed in a virtual machine by using
pktgen kernel module on the host and virtio-net in the guest. Since
there is no `ZeroCopyReadPacketData`, the `PfringReadZero` lines compare
`ReadPacketDataTo` in the old implementation with
`ZeroCopyReadPacketData` in the new version.

65536 byte size packets:
```
name              old time/op    new time/op    delta
PfringRead-2        47.5µs ±10%    42.8µs ± 7%    -9.85%  (p=0.012 n=8+10)
PfringReadZero-2    42.5µs ±25%    32.9µs ± 7%   -22.65%  (p=0.000 n=10+10)
PfringReadTo-2      42.5µs ±25%    36.8µs ± 9%      ~     (p=0.143 n=10+10)

name              old speed      new speed      delta
PfringRead-2      1.30GB/s ±26%  1.53GB/s ± 7%   +17.57%  (p=0.003 n=10+10)
PfringReadZero-2  1.58GB/s ±22%  1.99GB/s ± 7%   +25.90%  (p=0.000 n=10+10)
PfringReadTo-2    1.58GB/s ±22%  1.79GB/s ± 9%      ~     (p=0.143 n=10+10)

name              old alloc/op   new alloc/op   delta
PfringRead-2        65.6kB ± 0%    65.5kB ± 0%    -0.02%  (p=0.000 n=10+10)
PfringReadZero-2     16.0B ± 0%      0.0B       -100.00%  (p=0.000 n=10+10)
PfringReadTo-2       16.0B ± 0%      0.0B       -100.00%  (p=0.000 n=10+10)

name              old allocs/op  new allocs/op  delta
PfringRead-2          2.00 ± 0%      1.00 ± 0%   -50.00%  (p=0.000 n=10+10)
PfringReadZero-2      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=10+10)
PfringReadTo-2        1.00 ± 0%      0.00       -100.00%  (p=0.000 n=10+10)
```

58 byte size packets:
```
name              old time/op    new time/op     delta
PfringRead-2        46.8µs ±23%      3.2µs ±85%    -93.15%  (p=0.000 n=10+10)
PfringReadZero-2    2.48µs ±11%     2.33µs ± 2%     -6.37%  (p=0.022 n=10+8)
PfringReadTo-2      2.48µs ±11%     2.63µs ± 6%       ~     (p=0.053 n=10+9)

name              old speed      new speed       delta
PfringRead-2      1.27MB/s ±24%  21.17MB/s ±60%  +1570.88%  (p=0.000 n=10+10)
PfringReadZero-2  23.5MB/s ±10%   24.9MB/s ± 2%     +6.33%  (p=0.017 n=10+8)
PfringReadTo-2    23.5MB/s ±10%   22.0MB/s ± 6%       ~     (p=0.053 n=10+9)

name              old alloc/op   new alloc/op    delta
PfringRead-2        65.6kB ± 0%      0.1kB ± 0%    -99.90%  (p=0.000 n=10+10)
PfringReadZero-2     16.0B ± 0%       0.0B        -100.00%  (p=0.000 n=10+10)
PfringReadTo-2       16.0B ± 0%       0.0B        -100.00%  (p=0.000 n=10+10)

name              old allocs/op  new allocs/op   delta
PfringRead-2          2.00 ± 0%       1.00 ± 0%    -50.00%  (p=0.000 n=10+10)
PfringReadZero-2      1.00 ± 0%       0.00        -100.00%  (p=0.000 n=10+10)
PfringReadTo-2        1.00 ± 0%       0.00        -100.00%  (p=0.000 n=10+10)
```

### CODE REVIEW

**Comment by notti** [comment]
@gconnell any idea how govet fails here? The pfring directory isn't checked by govet, I didn't change anything outside it, and if I execute go vet on my computer there are no errors.

**Comment by notti** [comment]
ahh nevermind I looked at the wrong line

File: pfring/pfring_test.go [hunk 1]
```diff
@@ -0,0 +1,64 @@
+package pfring
```
Comment (gconnell) [inline pfring/pfring_test.go]: copyright.

Comment (notti) [reply pfring/pfring_test.go]: I knew I forgot something...
