### PR TITLE
Loosen error checking to allow blank DNS name fields which can be valid

### LINKED ISSUE #273: dns.go panic with root query response
I found a panic with a root query response.  Sanitized pcap attached.

[rootqueryresponse_sanitized_payload.pcap.zip](https://github.com/google/gopacket/files/655186/rootqueryresponse_sanitized_payload.pcap.zip)

panic: runtime error: slice bounds out of range

goroutine 12 [running]:
panic(0x7a0660, 0xc420012120)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/google/gopacket/layers.decodeName(0xc420073d6a, 0x1fc, 0x1fc, 0x4c, 0xc4201583a8, 0x1, 0x158, 0x2c0, 0x0, 0xc421124840, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:587 +0x6c2
github.com/google/gopacket/layers.(*DNSResourceRecord).decode(0xc421124998, 0xc420073d6a, 0x1fc, 0x1fc, 0x4c, 0x7f26c9c5e590, 0xc4210fd680, 0xc4201583a8, 0x4c, 0x0, ...)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:665 +0x6f
github.com/google/gopacket/layers.(*DNS).DecodeFromBytes(0xc420158300, 0xc420073d6a, 0x1fc, 0x1fc, 0x7f26c9c5e590, 0xc4210fd680, 0x1000, 0x1000)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:355 +0x74f
github.com/google/gopacket/layers.decodeDNS(0xc420073d6a, 0x1fc, 0x1fc, 0xc1cc80, 0xc4210fd680, 0x0, 0xc)
	/home/danm/work/src/github.com/google/gopacket/layers/dns.go:284 +0xb7
github.com/google/gopacket.DecodeFunc.Decode(0x864bc0, 0xc420073d6a, 0x1fc, 0x1fc, 0xc1cc80, 0xc4210fd680, 0x4218fe, 0xc41ff78873)
	/home/danm/work/src/github.com/google/gopacket/decode.go:85 +0x58
github.com/google/gopacket.LayerType.Decode(0x6b, 0xc420073d6a, 0x1fc, 0x1fc, 0xc1cc80, 0xc4210fd680, 0xc421199400, 0x422bc3)
	/home/danm/work/src/github.com/google/gopacket/layertype.go:95 +0xb1
github.com/google/gopacket.(*LayerType).Decode(0xc4211da060, 0xc420073d6a, 0x1fc, 0x1fc, 0xc1cc80, 0xc4210fd680, 0xc4211da060, 0xc4200358f8)
	<autogenerated>:14 +0x84

### PR DESCRIPTION
**Pull request by bmeadors**
It appears fix #273 was done to handle a buffer overrun panic in layers/dns.go.  The fix simply returns an error when decoding a DNS packet having an empty Name field.  An empty Name field is valid in some circumstances when referring to the root servers.  This PR loosens the restriction by not returning an error for the empty Name field and also properly adjusting the buffer index as to not recreate the original panic condition fixed by #273.

It seems the validation for the empty Name field would be better left up to the caller to decide if this should be treated as an error condition or not.  DNS packets with an empty Name fields can still be properly decoded and returned back to the caller to be dealt with there.

### CODE REVIEW

File: layers/dns_test.go [hunk 1]
```diff
@@ -576,10 +576,8 @@ var testMalformedRootQuery = []byte{
 
 func TestMalformedRootQuery(t *testing.T) {
```
Comment (notti) [inline layers/dns_test.go]: Could you rename the test. It still suggests the packet is malformed although it isnt.

File: layers/dns_test.go [hunk 2]
```diff
@@ -576,10 +576,8 @@ var testMalformedRootQuery = []byte{
...
 	p := gopacket.NewPacket(testMalformedRootQuery, LinkTypeEthernet, testDecodeOptions)
```
Comment (notti) [inline layers/dns_test.go]: Same for the variable containing the packet

File: layers/dns_test.go (hunk 1 above)
Comment (bmeadors) [reply layers/dns_test.go]: Changed to TestBlankNameRootQuery.

File: layers/dns_test.go (hunk 2 above)
Comment (bmeadors) [reply layers/dns_test.go]: Changed to testBlankNameRootQuery.

**Comment by notti** [comment]
Thanks for the fix.
